click-drop mechanics
gbtami/pychess-variants pull request #584
Opened 2021-07-31 23:13 UTC by nnickoloff1234

Improvements for https://github.com/gbtami/pychess-variants/issues/5

Should be merged together with the corresponding PR in chessgroundx

2021-08-12 16:02 UTC, Fulmene requested changes

2021-08-12 16:02 UTC, Fulmene commented on client/analysisCtrl.ts
> +import {dropIsValid, pocketView, updatePockets, Pockets, refreshPockets} from './pocket';
Please add a space after open bracket and before close bracket. This applies everywhere.

2021-08-12 16:02 UTC, Fulmene commented on client/pocket.ts
> +const eventNames2 = ['click'];
I'd appreciate more descriptive names for these two.

2021-08-12 16:02 UTC, Fulmene commented on client/pocket.ts
> +    const roles = Object.keys(pocket);//contains the list of possible pieces/roles (i.e. for crazyhouse p-piece, n-piece, b-piece, r-piece, q-piece) in the order they will be displayed in the pocket
Please add one space before inline comment. This applies everywhere.

2021-08-19 11:30 UTC, Fulmene approved these changes

2021-08-19 11:39 UTC, merged

2021-08-19 11:39 UTC, gbtami commented
Thx a lot!